/*
 * globals.h
 *
 *  Created on: 12-Mar-2020
 *      Author: sajetan
 */

#ifndef INCLUDE_COMMON_GLOBALS_H_
#define INCLUDE_COMMON_GLOBALS_H_


enum LIFT_DRONE_SESSION_STATES {
	DRONE_SESSION_EST_INIT = 0,
	DRONE_SESSION_EST_WAIT_RESPONSE,
	DRONE_SESSION_EST_VERIFY_RESPONSE,
	DRONE_SESSION_EST_WAIT_COMMUNICATION,
	DRONE_SESSION_EST_TERMINATE,
} ;

enum LIFT_BST_SESSION_STATES {
	BST_SESSION_EST_INIT = 0,
	BST_SESSION_EST_WAIT_RESPONSE,
	BST_SESSION_EST_VERIFY_RESPONSE,
	BST_SESSION_EST_WAIT_COMMUNICATION,
	BST_SESSION_EST_TERMINATE,
} ;



#endif /* INCLUDE_COMMON_GLOBALS_H_ */
