/*
 * control_includes.h
 */

#ifndef INCLUDE_CONTROL_INCLUDES_H_
#define INCLUDE_CONTROL_INCLUDES_H_

typedef enum {
	CONTROL_SESSION_INIT = 0,
	CONTROL_SEND_PUBLIC_KEY,
	CONTROL_CALCULATE_SESSION_KEY,
	CONTROL_SESSION_COMMUNICATION,
	CONTROL_SESSION_TERMINATE
} LIFT_CONTROL_SESSION_STATES;


#endif /* INCLUDE_CONTROL_INCLUDES_H_ */
